### ISSUE TITLE
Concurrency Issue with handling the updated resource after reconciliation.

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#1006]
(This part was reworked for 2.2.0 already, that is not effected)

**Comment by andreaTP** [comment]
The issue have been detected and reproduced in the Keycloak Operator CI.

Those are the relevant logs: [16_Build (16).txt](https://github.com/java-operator-sdk/java-operator-sdk/files/8212904/16_Build.16.txt).
And this is the code for reproducing (under the `operator` module):
https://github.com/andreaTP/keycloak/tree/check-ci-stability

The sequence of events that is triggering the issue looks as follows:

 - reconciliation in progress
 - receiving an event from k8s (and recociliation is skipped) [event 1]
 - reconciliation finishes and updates the status stanza of the CR
 - receiving an event from k8s because of the modified status (and it gets skipped) [event 2]
 - despite the fact that [event 1] hasn't been processed no reconciliation loop is scheduled
 - following "scheduled reconciliations" (with `rescheduleAfter`) are ignored too

I do believe that this is a critical bug and we should rise the attention on upgrading in the upcoming release notes.
Thanks @csviri for the support in debugging!

**Comment by andreaTP** [comment]
For the records:
As a temporary workaround setting `generationAwareEventProcessing = false` in the `ControllerConfiguration` prevent the issue from rising.

**Comment by andreaTP** [comment]
I confirm that the upcoming `SNAPSHOT` release fix the issue 🎉 
Thanks!
