### ISSUE TITLE
Operator should not have to read CustomResourceDefinitions on startup

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#104]
Currently the operator gets certain CRD values from the cluster during startup by get-ing the CRD (Operator.java:89). This means that the Operator needs access to list and get CRDs on the cluster to do this single operation.

We could store the CRD next to the source code in the jar file and read these values from there.

**Comment by csviri** [comment]
It does not need to list, just read with a name.

Maybe this should be done together with the POJO generation from CRD.

It might be also interesting to think of, if we don't read from server how do we know that we handle the up to date one (like regarding versions of resources etc). So maybe we would like to check (optional feature? ) if that is on classpath is equal to the one on the serve (that always needs to be there). Just brainstorming here..

**Comment by jmrodri** [comment]
@metacosm please review and if it is obsolete please close.

**Comment by metacosm** [comment]
This issue is obsolete: CRD access is only needed if the user wants to validate that the CRD exists on the cluster or check that the proper scope is used for custom resources. Both aspects are controlled by a configuration option (`JAVA_OPERATOR_SDK_CHECK_CRD` system property for the plain java version) which allows to disable the feature if needed.
