### ISSUE TITLE
Cannot get secondary resource from context after operator restart

### ISSUE THREAD

**Issue by morhidi** [java-operator-sdk/java-operator-sdk#1299]
Hi folks,

users encountered a blocking issue [FLINK-28008](https://issues.apache.org/jira/browse/FLINK-28008) in Flink Kubernetes Operator related to primary/secondary resources after upgrading it to JOSDK v3.0.2.

We are managing session jobs(primary resource) and session clusters(secondary resource) with the Operator. Once a session job finishes users usually delete it. However, when the Operator is restarted, newly submitted session jobs won't find the session cluster anymore. The session cluster must be deleted and recreated to make it work which is not an acceptable workaround in our case unfortunately. I've uploaded the repro logs [here](https://gist.github.com/morhidi/7e5b79217436b57e23dd38a61dc1f3df)

Could you please take a look into this issue?

Thanks,
Matyas

**Comment by csviri** [comment]
thx @morhidi, will take a look. This on first guess could be related to the ordering of event sources and their indexes, will dig deeper, and try to come up with some solution.

**Comment by csviri** [comment]
The problem is when there is "many-to-one" or "many-to-many" relationship between the primary and the secondary resources. 
Create an integration test to reproduce this issue, you can see when it is happening:
https://github.com/java-operator-sdk/java-operator-sdk/blob/80fb6fc4430f2e1ba9a874e0327f148b4a0d1873/operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/primarytosecondary/JobReconciler.java#L17-L17

This replicates the case for Flink Operator.
Unfortunatelly there is no efficient way to cover this, other way then using a `PrimaryToSecondary` mapper. Will provide the fix. You can already see how it will work from the link above.

**Comment by csviri** [comment]
added docs here: https://javaoperatorsdk.io/docs/features#managing-relation-between-primary-and-secondary-resources
