### ISSUE TITLE
Investigate if all state associated with a given resource could be managed in a single spot 

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#1314]
Candidate states to be unified: retry, event marker, rate limiting…
The most likely spot would be `EventProcessor`. 

Pros:
- state is managed in a single spot and `EventProcessor` knows when the state needs to be modified / cleaned-up
- would simplify moving to a multi-cluster model since how resource state is tracked would be more localised instead of spread in different spots

Cons:
- probably needs to abstract state in a generic way

**Comment by csviri** [comment]
> state is managed in a single spot and EventProcessor knows when the state needs to be modified / cleaned-up

Now this would help probably just with the cleanup. Also in the background we won't use 3 HashMaps just 1. 

> probably needs to abstract state in a generic way

Yes, this would mean rate limiter needs a spefic api for execution state, separated, what is not nice, since this does not fit well to the rate limiter API. 

Something similar would hold for event marker. That is not exposed, so would not be such an issue.
