### ISSUE TITLE
Resizing PVCs using dependant resource

### ISSUE THREAD

**Issue by prabhjotlalli** [java-operator-sdk/java-operator-sdk#1652]
#### What did you do?

I'm trying to write some DependantResources to upgrade my PVC sizes automatically. I'm looking to allow my clients to upgrade their storage size for running pods. Currently I have to manually
1. Delete (with orphan pods) the StatefulSet
2. Update the storage in each PVC
3. Recreate the StatefulSet with the new storage size.

#### What did you expect to see?

I tried to write a reconciler that has both PVC and StatefulSet but I think they'd conflict in trying to create/update each PVC with subsequent updates of storage size. I'd have undefined behaviour (it seemed like it worked sometimes and other times using `csi-snapshotter`, I'd see both my PVC dependant resource and the StatefulSet dependant resource try to create the PVC and then a random delete call and no PVC would be created).

#### What did you see instead? Under which circumstances?

I was hoping to get some guidance on how to achieve what I'm doing. My current plan is to :
1. Create all my other resources as dependant resources
2. I then check if StatefulSet exists. If it does delete it (orphan pods)
3. Recreate StatefulSet with new storage size
4. Update PVC storage sizes
5. Emit a rolling restart call to the pods when PVCs say resizing is ready for pods to restart
6. Set status and consider reconciling done

But I feel like I'm not doing it the way the framework would expect me to.

#### Environment

**Kubernetes cluster type:**

vanilla local development (csi-snapshot for my storage class)
GKE for production (ssd for my storage class)

`$ Mention java-operator-sdk version from pom.xml file`

4.1.0

`$ java -version`

openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+9-61)
OpenJDK 64-Bit Server VM (build 18.0.2+9-61, mixed mode, sharing)

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-dispatcher", GitCommit:"2a8027f41d28b788b001389f3091c245cd0a9a60", GitTreeState:"clean", BuildDate:"2022-01-21T20:31:13Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}

**Comment by csviri** [comment]
Hi @prabhjotlalli ,

sorry for late response, I think this might be possible with dependent resources, but given the simple workflow, it might be just easier to do with low level API.

However if you still want to do it with dependent resources:

> Create all my other resources as dependant resources

This is the easy part, just list them as a dependent resource

> 2. I then check if StatefulSet exists. If it does delete it (orphan pods)
> 3. Recreate StatefulSet with new storage size

This sounds to be as a StatefulSet dependent resource with a special pre-condition, where you will check if the resource needs to be created or not. It is also NOT if you want to delete it - if a precondition is false it will be deleted - after deleted on next reconciliation will recreate it again (You just use the storage sizes and other infor from CR or context). 

> 4. Update PVC storage sizes

This is insteresting, but I assume the main problem is that it needs to be done after the StatefulSet is update. Although cannot really dependent on it, since it would be also deleted if the precondition not holds. So here the trick would be to do it as an independent dependent resource, and in the desired state check the StatefulSet storage size. 

> 5. Emit a rolling restart call to the pods when PVCs say resizing is ready for pods to restart

That should be trivial: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets

> 6. Set status and consider reconciling done

Also this is trivial.

To be honest I don't have to much experience with PVC resizing, not sure if this needs to be this complicated, with the deleting the pods, usually I would expect in K8S , that it is enough to update the PVC and StatefulSet that makes this much simpler.
