### ISSUE TITLE
CI E2E tests should run on k8s matrix 

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#1663]
The e2e tests are currently using a rather old, hardcoded k8s version. They should run on the same matrix as the rest of the tests.

**Comment by csviri** [comment]
For now added this PR: https://github.com/java-operator-sdk/java-operator-sdk/pull/1713

I'm not sure if this should run on the full matrix, would say rather the newest k8s, since integration tests are intended to cover all the features already. So this is more to test the whole deployment, and real life scenario. Would not harm though.
