### ISSUE TITLE
leader-election support multi cluster

### ISSUE THREAD

**Issue by hkmdxlftjf** [java-operator-sdk/java-operator-sdk#1817]
#### What did you do?

an instance watch multi-cluster event, but only one election

#### What did you expect to see?

https://github.com/java-operator-sdk/java-operator-sdk/blob/3812a7fe73f81033d87297afd3081a93760a7abd/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java#L76  
can support custom kubernetes-client

**Comment by csviri** [comment]
Hi @hkmdxlftjf , I'm not sure I uderstand what are you asking for, could you describe your use case?

**Comment by hkmdxlftjf** [comment]
we have multi k8s clusters, I want to deploy the operator on a cluster and namespace is xxxx, watch all cluster cr events, 
eg:
`Map<String, Operator> clusterWithOperator = new HashMap<>();`
when isLeaderElectionEnabled is true,  new Operator() will create lease on a different cluster，expect to create a lease only on the deployed cluster, or i can specify the cluster(kubernetes client)

**Comment by csviri** [comment]
Ok, so currently you can do this just not using the leader election capabilities of the JOSDK, and just setup leader election with fabric8 client, and start the operators if becomes the leader.  
The downside is that the non-leader operator does prepares the caches, so when one them becomes the leader it might take some time until the resources are processed on startup on large clusters. 

So if I understand the problem what you asking for is to be able to specify the client for leader election. 
Will have to take a look because this not necessarily will solve the problem. Since you will have multiple operators competing for the lease, even if they have the same ID (in terms of leader election), this might not work. Will have to think about it / check it.

**Comment by hkmdxlftjf** [comment]
can i try add attributein leaderelectionconfiguration(KubernetesClient client), and provide a method to use modify this attribute

**Comment by csviri** [comment]
you are always free to issue a pull request, and we can take a look. But would require a test for this, pls see current leader election tests. 

I will also take a look on the implementation of the leader election, since there might be conceptual issue with this approach. Since in this case it is more like about having multiple leaders instead of one with same `identity` and the leader election was not designed for this.  (But will try the best to support your use case). 

cc @shawkins

**Comment by csviri** [comment]
Will take a look but I think the proper solution here is to share the `LeaderElector` between multiple controllers, not create `LeaderElector` for each `Operator` with the same client. Will take a look how feasible is this to implement.

**Comment by csviri** [comment]
@hkmdxlftjf Also note that leader election does not give you that much, so if pod crashes and restarts is good enough in most of cases.

**Comment by csviri** [comment]
@hkmdxlftjf  can we close this issue too?

**Comment by hkmdxlftjf** [comment]
@csviri  yes
