### ISSUE TITLE
Investigate supporting webhooks

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#370]

**Comment by lburgazzoli** [comment]
There are some cases where a web-hook may be useful, as example, supporting for upgrading custom resources when an operator gets updated or to do validation that go beyond what you can do with declarative validation. I don't have a clear idea how that should be implemented but it is not really different from a controller so as a developer, I'd expect to see something like:

```java
@Admission
class MyDefault implements Defaulter<T> {
    void setDefaults(T resource) { 
    }
}

@Admission
class MyValidator implements Validator<T> {
    void validateCreate(T resource) throws ValidationException { 
    }
    void validateUpdate(T oldResource, T newResource) throws ValidationException { 
    }
    void validateDelete(T resource) throws ValidationException { 
    }
}
```

And have `dekorate` generating the required resources.

**Comment by csviri** [comment]
If I understand correctly this is about admission controller is general:
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

Just some notes:

-  I this not necessarily should be part of the Operator part of the SDK, probably a new project. Since admission controllers are all about exposing a web-service interface. We could facilitate that, so make it very easy to generate the JSON Patches, exposing the default API-s. Just not sure how hard is it to do from scratch, since the model is already there in Fabric8 client, 
see: https://javadoc.io/static/io.fabric8/kubernetes-model/4.6.4/io/fabric8/kubernetes/api/model/admission/AdmissionResponse.html
So maybe I would just start writing a simple Admission controller, and see what is missing from the experience

**Comment by csviri** [comment]
Created a simple prototype please let us know what do you think:
https://github.com/java-operator-sdk/admission-controller-framework

**Comment by csviri** [comment]
Although the framework is as very thin layer, supporting testing and other aspects like generating yaml for Webhook configuration really could increase the productivity, mainly the initial step. So will continue examining it,
