### ISSUE TITLE
Resource status is NULL when using java-operator controller with kubernetes mock server

### ISSUE THREAD

**Issue by maledoux** [java-operator-sdk/java-operator-sdk#396]
I am trying to write unit tests for my java-operator using the kubernetes-server-mock.

I am using these versions:
```
        <operator-framework>1.8.2</operator-framework>
        <version.fabric8.client>5.3.0</version.fabric8.client>
        <kubernetes-server-mock.version>5.3.0</kubernetes-server-mock.version>
```

My unit test simply create an operator with a controller, loads a CRD, and creates a resource for the CRD.

When I hit createOrUpdateResource() in the controller, the status of the resource is null, see image below.

![image](https://user-images.githubusercontent.com/20685776/115067618-2e708400-9ebf-11eb-9d15-a1b5888a874e.png)

I tried again using 
`        <version.fabric8.client>5.1.1</version.fabric8.client>`

The status now has a non-null reference, which is fine... But now I run into another problem. 
Everytime a call to **return UpdateControl.updateStatusSubResource(myResource)** is made, I get called back immediately in **createOrUpdateResource()** with a different resource UID and the reconcile process goes into an infinite loop, calling **createOrUpdateResource()** over and over again.

**Comment by metacosm** [comment]
Is the status null after you set it? It's normal that status is initially null if the controller has never set it and the resource has just been created (i.e. it doesn't have a status on the server).

**Comment by maledoux** [comment]
I created my resource the same way I would with the real Kubernetes client in a real cluster, so I would expect the status to be non-null.

I find it odd that version 5.1.1 does not behave the same way than version 5.3.0 with the server mock for this.

**Comment by metacosm** [comment]
The handling of status and spec has indeed changed between 5.1.1 and 5.3.0. In 5.1, we were automatically instantiating these fields for Custom Resources but that turned out to  cause more issues than solve.

If a resource is applied to a cluster but no controller handles it, it's expected that it's status should be null because there's nothing to update that status, btw. So a null status is expected for any resource that has not yet be handled by a controller, in my opinion. In that respect, the 5.1 behavior was wrong.

**Comment by maledoux** [comment]
Ok, I just looked un the mysql schema sample and the status is actually created in the createOrUpdateResource().
 I will change my controller accordingly.

Have you looked at the other problem where updateStatusSubResource() triggers a call to the controller with a different UID everytime. This only happens with the mock server for my unit tests, otherwise it works fine using the production environment.

**Comment by shawkins** [comment]
I wanted to add a few things here.  It took some changes in fabric8 to get mock stuff working with the operator sdk.  https://github.com/fabric8io/kubernetes-client/pull/2946 and https://github.com/fabric8io/kubernetes-client/pull/2943 - those are both in 5.3.0.  If you use an older fabric8 things won't work at all because expected fields will be missing.  There is still https://github.com/fabric8io/mockwebserver/pull/59 needed to infer the appropriate namespace for created resources, but you can workaround that by making sure the resource metadata specifies a namespace.

> Have you looked at the other problem where updateStatusSubResource() triggers a call to the controller with a different UID everytime. This only happens with the mock server for my unit tests, otherwise it works fine using the production environment.

If you have found some other behavior that doesn't seem right, please capture that as a fabric8 issue - I'd like to have the mock work reasonably well with the sdk.  I haven't gone back to look at the mock behavior more after those initial prs because it seemed to work well enough for our controller.

**Comment by jmrodri** [comment]
@maledoux could you try this out again, there was a change made that would likely fix this issue for you.

**Comment by laxmikantbpandhare** [comment]
The older version of `Fabric8` (`5.1.0`) used to set the fields of Custom Resource. The newer versions of `Kubernetes client` (`5.3.0`) does not set fields of Custom Resource automatically as explained earlier. Below are the examples for reference where you can create `status` in Controller according to your needs.

https://github.com/java-operator-sdk/samples/blob/main/mysql-schema/src/main/java/io/javaoperatorsdk/operator/sample/MySQLSchemaController.java#L75

https://github.com/java-operator-sdk/samples/blob/main/webserver/src/main/java/io/javaoperatorsdk/operator/sample/WebServerController.java#L109

We are closing this issue at the moment. Please let us know if you come across any issues with `java-operator-sdk`.
