### ISSUE TITLE
EventSourceManager interface

### ISSUE THREAD

**Issue by lburgazzoli** [java-operator-sdk/java-operator-sdk#405]
the EventSourceManager interface defines a method that looks lika an internal one:

```java
Optional<EventSource> deRegisterCustomResourceFromEventSource(...);
```

It looks like the only usage, is an internal implementation detail of the `DefaultEventSourceManager` so it may be safe to remove it.

**Comment by teszes** [comment]
Wouldn't removing a public interface method mean a new major API version? I mean don't we have guarantees that public interfaces remain stable on minor versions with respect to only adding methods, not change or remove them?

I'm all for doing this if this is something we don't want people to build on.

**Comment by lburgazzoli** [comment]
the EventSourceManager seems really an internal class, so yes it would break the interface but I looking at the code it does not seems to me that EventSourceManager/DefaultEventSourceManager can easilly be replaced

**Comment by csviri** [comment]
The EventSourceManager interface it just really about what we expose in the controller, so the user does not see the implementation and other methods. So its about interface segregation principle. I agree that `deRegisterCustomResourceFromEventSource` should be removed. Since we don't se any dynamic registration and deregistration happening in the controller (just once in init method)
