### ISSUE TITLE
Operator start behavior

### ISSUE THREAD

**Issue by lburgazzoli** [java-operator-sdk/java-operator-sdk#408]
The Operator.start method is implemented like:

```java
public void start() {
   ...
    try {
      ...
    } catch (Exception e) {
      log.error("Error retrieving the server version. Exiting!", e);
      System.exit(1);
    }
  }
```

I wonder if instead of doing a `System.exit(1)`, the start method should thrown an exception and let the caller decide what to do.

**Comment by teszes** [comment]
I second this, this could just throw an OperatorException and go on from there. System.exit(1) won't even produce a clean halt, so it's just an unhandled (and unhandleable) exception with less information on the output.

**Comment by metacosm** [comment]
@lburgazzoli do you have a specific use case or issue with the current handling? The idea here, which might be misguided, is that if the operator fails to start then that's usually a non-recoverable error and the pod the operator runs in should crash so that Kubernetes gets the opportunity to re-schedule a new pod at some later time.

**Comment by lburgazzoli** [comment]
That's ok but it is not possible to intercept the error, so for example if we are using quarkus, I may want to use Quarkus.asyncExit() instead of using System.exit()
