### ISSUE TITLE
Broken links on landing page

### ISSUE THREAD

**Issue by gunnarmorling** [java-operator-sdk/java-operator-sdk#449]
The links to Tomcat.java, DeploymentEventSource.java, and QuarkusOperator.java on https://javaoperatorsdk.io yield 404s. I'll be happy to send a PR if you tell me where's the source of that page and where those links should point to. Thx!

// CC @metacosm

**Comment by teszes** [comment]
Hi @gunnarmorling, thanks for pointing this out and the offer to help.

I think this is related to moving the samples to different repos.
DeploymentEventSource is now here:

https://github.com/java-operator-sdk/samples/blob/main/tomcat/src/main/java/io/javaoperatorsdk/operator/sample/DeploymentEventSource.java

Haven't seen the other files, the quarkus operator might be in the quarkiverse project, @metacosm might know more about that.

Tomcat.java must have been renamed.

On this note, can we have a discussion on the repo names under the project? If we want a merge-from-private-fork workflow, the repo "samples" for example is not too informative. I have a teszes/samples fork, and I imagine others might just have a different samples repo in their profile. Can we rename it to java-operator-sdk-samples for example?

Another thing, I've seen that there is an archived tomcat operator project that I presume has been merged to the samples repo, but since we haven't so many repos as of now, it might make sense to have samples in their own repos like tomcat was. It could ease the workflow where if I want a new operator developed, I could just clone a sample repo and have the project structure set up instead of copying files around.

**Comment by jmrodri** [comment]
This has been addressed. If you still find an issue please re-open.
