### ISSUE TITLE
ConfiguredController behavior

### ISSUE THREAD

**Issue by lburgazzoli** [java-operator-sdk/java-operator-sdk#554]
I see that the ConfiguredController has an [init](https://github.com/java-operator-sdk/java-operator-sdk/blob/master/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/ConfiguredController.java#L106-L110) method in which does:

```java
@Override
public void init(EventSourceManager eventSourceManager) {
  this.manager = eventSourceManager;
  controller.init(eventSourceManager);
}
```

So the underlying controller is initialized with the manager that is passed as an argument. But then the [start](https://github.com/java-operator-sdk/java-operator-sdk/blob/master/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/ConfiguredController.java#L159) method does something similar:

```java
try {
  DefaultEventSourceManager<R> eventSourceManager = new DefaultEventSourceManager<>(this);
  controller.init(eventSourceManager);
} catch (MissingCRDException e) {
  throwMissingCRDException(crdName, specVersion, controllerName);
}
```

Wonder if this is correct or if this lead the controller to be initialized with two different event source manager.

**Comment by metacosm** [comment]
I don't really like this method, to be honest. It feels like abstraction leaking out. That said, there shouldn't be an issue because the `init` method is only called internally as a way to pass the `EventSourceManager` implementation to the controller implementations so that they can register their `EventSource` implementations and `ConfiguredController.init` should actually never be called. Maybe we could replace that implementation by `throw new UnsupportedOperationException` or something like that to make it clearer?
