### ISSUE TITLE
Q) Is the `shouldUpdateObservedGenerationAutomatically` logic working as intended in the post-processing of update Control?

### ISSUE THREAD

**Issue by heesuk-ahn** [java-operator-sdk/java-operator-sdk#762]
## Description

While looking through the update Control post-processor code, I found something a bit ambiguous.

https://github.com/java-operator-sdk/java-operator-sdk/blob/5955ecd1dd1ff0886aabee5a441e2664b392ca5e/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java#L154-L156

```
      updatedCustomResource = updateCustomResource(updateControl.getResource());

      if (shouldUpdateObservedGenerationAutomatically(updatedCustomResource)) {
        updatedCustomResource = updateStatusGenerationAware(originalResource); 
      }
```

In this code, you checked observedGeneration for `updatedCustomResource`, but the `updateStatusGenerationAware` method is actually being used for the `originalResource`.

In this case, instead of the customResource updated by the user, `originalResource` will be used as updatedResource.

```
      updatedCustomResource = updateCustomResource(updateControl.getResource());

      if (shouldUpdateObservedGenerationAutomatically(updatedCustomResource)) {
        updatedCustomResource = updateStatusGenerationAware(updatedCustomResource);  // << use updatedCustomResoruce instead of original
      }
```

In my opinion, isn't it the intended behavior that needs to be modified as above?

**Comment by csviri** [comment]
Hi @heesuk-ahn 
this is intentional,  we don't want to do anything that is against the intention of the user, here the user intends to update the custom resource but not the status sub-resource. However the status POJO might or might not have changed during the reconciliation. So if we would update the observedGeneration on that status there might be a side effect that update the status with actual non desired changes. 
So here instead we take the original status, and change the observedGeneration there and make the subsequent call to update the status sub-resource. Maybe this should be described as a comment in the code.
