### ISSUE TITLE
[feature] Easy way to detect external modification to owned resources

### ISSUE THREAD

**Issue by andreaTP** [java-operator-sdk/java-operator-sdk#829]
When a reconcile loop is triggered because of the change of one of the owned resources it should be easy to detect if the change was done by the operator itself or someone manually modified the resource.

A concrete use case is the following:
 - the controller read a CRD and create a `Deployment`
 - the `Deployment` gets manually patched in the cluster
 - the operator should easily detect the situation and restore the desired `Deployment`

**Comment by metacosm** [comment]
I'm not sure I understand the issue here. When the `Deployment` is updated, your reconciler will get triggered and then you use the desired state as recorded by the custom resource the SDK passes to you to decide what needs to be done. Concretely, if the `Deployment` is manually patched, then its state won't match the desired state as defined by your CR spec. Your reconciler is supposed to check all its dependent resources and query their state to see if it matches the desired state. There is no way to determine generically and efficiently what needs to be changed in the cluster state when your reconciler is triggered since it depends on your controller's logic.

That said, the work on dependent resource could expose hooks on each `DependentResource` "handler" for user to report diffs between the desired and actual state to make the process a little easier but ultimately, it's still up to the developer of the operator to figure out how what has changed on the cluster and what needs to be adjusted when the reconciler gets triggered.

**Comment by andreaTP** [comment]
@metacosm that's very correct, but, at the moment the operator developer should "manually" roll out the diff checking, and I do believe that there is space for improvement there from the SDK side.
For example the SDK can provide utilities to compare desired state and actual state and return the diff.

**Comment by csviri** [comment]
Maybe we could rename the issue or close this one and create a new for the utility of diff checking, to forgo the misunderstanding.

**Comment by csviri** [comment]
By the desired state I mean the `.spec` of the resource. So the workflow is:

1. get the cached resource - in our sample the `Deployment`
2. calculate the Deployment that we we would create if this deployment would not exists
3. Compare the spec part of the 2 resources
4. if its different apply the calculated Deployment

**Comment by metacosm** [comment]
The problem is that you cannot do step 2 at the moment. There's no support for this. Like I said the dependent resources work helps there.

**Comment by csviri** [comment]
Absolutely, what we can do now is just a simple utility,
`Util.compareAndApplyIfDifferent(currentDeployment,targetDeployment,kubernetesClient)`
maybe with suppliers etc or other fancy variant  :)

**Comment by metacosm** [comment]
Yes, the problem is computing `targetDeployment` in this example. However, like I said this problem is solved by the dependent resources work with the `Builder` interface which role is exactly to create a representation of the desired dependent resource based on the state of the primary one.

**Comment by andreaTP** [comment]
As I understand it `targetDeployment` will come from the user business logic.

**Comment by csviri** [comment]
Yes, that is anyway, the case, regardless this is part of dependent resources or not. Such utility methods are helpful, also for the future if somebody won't use dependent resources for example, just the current API.

**Comment by metacosm** [comment]
I believe this is fixed with the `Matcher` interface and the work done on dependent resources.

**Comment by csviri** [comment]
Yes, I think too,  we can close this.
