### ISSUE TITLE
Infinite loop of exhausted retries on error

### ISSUE THREAD

**Issue by scrocquesel** [java-operator-sdk/java-operator-sdk#911]
#### What did you do?

The operator throw an error during reconciliation. When retries are exhausted, the `updateErrorStatus` is called. As the documentation explains it, a event is trigger. But if the error is persistent, reconcile will exhausts retries, and loop.

If no retry is configured, then the loop is instantaneous and consumes lot of compute resources.

#### What did you expect to see?

If possible, the event received from updating the sub status on last attempt should be discarded.

#### Environment

**Kubernetes cluster type:**

Fabric8 mock server

**java-operator-sdk version**

2.0.2

**Comment by csviri** [comment]
@scrocquesel just to verify if I understand the concrete issue. In the status assume there is a field that changes on every execution? Otherwise there would no event since that would be no update, right?

Otherwise it make sense, in general after last retry or if no retry there should not be a reconciliation triggered by a status updtade if it is done by error handler. Is this how do you mean it?

**Comment by scrocquesel** [comment]
> @scrocquesel just to verify if I understand the concrete issue. In the status assume there is a field that changes on every execution? Otherwise there would no event since that would be no update, right?

Yes, I set a timestamp of when the error occured in a Condition. Seems, it's not a best practice.

> Otherwise it make sense, in general after last retry or if no retry there should not be a reconciliation triggered by a status updtade if it is done by error handler. Is this how do you mean it?

Yes.

**Comment by csviri** [comment]
Yes for now would just replace that variable part. See if that helps, then we can see how to handle this more nicely impelemtation wise.
