### ISSUE TITLE
Figure out whether we can avoid returning `Optional` for `DependentResource.eventSource`

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#938]

**Comment by csviri** [comment]
We should mainly consider it because of external resources, and for use cases when the reconciliation is periodically executed - not triggered by infermers.

Let's say the controller manages a set of external resources, one way to implement this is just to add periodic execution for the controller, so it checks all the resource states, and reconciles them. In this case no need for an event source.
