### ISSUE TITLE
[Request] Adding old resource to Reconciler's Context

### ISSUE THREAD

**Issue by asardaes** [java-operator-sdk/java-operator-sdk#952]
Hello, I have a use case in which the reconciliation logic changes slightly if a field in the resource changes from one specific value to another or viceversa. I don't think I can detect that with the current API because the old instance of the resource is not passed to the reconciler, but please correct if me if I'm wrong. I was thinking of adding a custom filter that injects custom flags into the resource that will be passed to the reconciler, but that feels pretty hacky.

**Comment by csviri** [comment]
Hi @asardaes, yes that is quite hacky, and especially it won't work if the operator restarts since the in memory state would be lost. If you need to store an explicit state you can put it into status, or rather a secret or config map. This is briefly touched in the state management in the docs:
https://javaoperatorsdk.io/docs/patterns-best-practices

**Comment by metacosm** [comment]
Yes, what you're trying to accomplish kind of goes against the Kubernetes philosophy where you're supposed to react to state, not transitions (because due to the distributed nature of a cluster, you might miss transitions for a variety of reasons), so generally speaking, your CR should be reconcilable based on a standalone state. Your operator can sort of record transitions using your CR status, though.

**Comment by asardaes** [comment]
Ah, I should have mentioned that due to some limitations, the resources I'm monitoring right now are Config Maps, which don't have status unfortunately. Nevertheless, I can find alternatives, but I'll first give some thought to what you mention regarding reconciliation philosophy.
