### ISSUE TITLE
Resync events are not passed to registered filters

### ISSUE THREAD

**Issue by asardaes** [java-operator-sdk/java-operator-sdk#980]
Hello, I have a reconciler that registers a `ResourceEventFilter` as well as a short-ish resync interval. Based only on the logs from my classes, I can see that the events received during resync are never processed by the filter, but they are seen by the reconciler. Is this by design?

**Comment by csviri** [comment]
Hi @asardaes , what exactly you mean by resync interval in this case, what configuration?  
`ResourceEventFilter` now applies now just on events for the custom resources. The periodic reconciliation is not implemented using resync intervals. So that is right, it will not receive the events for `reconciliationMaxInterval` from `@ControllerConfiguration` if you mean that.

**Comment by asardaes** [comment]
Hi, yes, I was talking about `reconciliationMaxInterval`, I also use some informers directly with fabric8's client, that's why I thought it was related to that kind of resync. Is there more information about the reconciliation mechanism then? I think it's causing some weird race conditions because it doesn't go through the filters.

**Comment by csviri** [comment]
@asardaes can you be more specific what are you seeing? Maybe some logs.

This is a relatively new feature, but basically it works that after reconciliation registers a timed event. The concurrency related logic is handled on a lower layer and it's independent from informers, that should not be an issue because of this.

Also note, that how it is mentioned in docs, this is meant to be rather a fail-safe, ideally you have informers and event sources to reconcile just on changes.

**Comment by asardaes** [comment]
Sorry, I guess I mixed some topics in an uninteded way. I didn't mean that my reconciler also has an informer or anything like that, I just meant that I've used informers in other projects, so when I saw the `reconciliationMaxInterval` options in this SDK, I thought it would simply pass that value to fabric8's classes to configure resync.

I think my intention is similar to #870. I have this in my filter class:

```java
private static final ConcurrentMap<String, String> VERSIONS = new ConcurrentHashMap<>();

public static void skipOneChangeAfter(ObjectMeta resourceMeta) {
    VERSIONS.put(resourceMeta.getName(), resourceMeta.getResourceVersion());
}

@Override
public boolean acceptChange(ControllerConfiguration<T> configuration, T oldResource, T newResource) {
    String oldVersion = oldResource == null ? "" : oldResource.getMetadata().getResourceVersion();
    ObjectMeta newMeta = newResource.getMetadata();

    boolean shouldSkip = oldVersion.equals(newMeta.getResourceVersion()) ||
            oldVersion.equals(VERSIONS.get(newMeta.getName()));

    return !shouldSkip;
}
```

The goal was to skip changes when `resourceVersion` didn't change, or it matches a version that I know will change because I update the resource. However, I noticed that during periodic reconciliation the reconciler still received events where `resourceVersion` didn't change.

I find it odd that filtering doesn't apply to periodic reconciliation, but if that's by design, I guess it could at least be documented?

**Comment by csviri** [comment]
> The goal was to skip changes when resourceVersion didn't change, or when it matches a version that I know will change because I updated the resource in the reconciler. However, I noticed that during periodic reconciliation the reconciler still received events where resourceVersion didn't change.

Basically, as said before this is a fail-safe, if you want just to react on changes of the custom resource, you don't have to do anything that is by default. The `resourceVersion` changes are filtered out by the generation awareness (`generationAwareEventProcessing`), what is by default turned on also. 

I understand this might be different from controller runtime, which contains such failsafe too (but not sure how it is implemented there).

Create a PR to improve javadoc: https://github.com/java-operator-sdk/java-operator-sdk/pull/984

The docs mentions this periodic reconcile, not sure this should be explicitly mentioned in the `Max Interval Between Reconciliations` section, since it is really don't have anything to do with resources. So would rather stick with that part as it is in the docs.
https://javaoperatorsdk.io/docs/features

**Comment by asardaes** [comment]
Right now I'm handling Config Maps, which don't have generation, so `generationAwareEventProcessing` is disabled in my case.
